---
title: "plot pred diffs maps"
author: "Dana K Briscoe"
date: "`r Sys.Date()`"
output: html_document
params:
  source: 'glorys'
  # source: 'gcm'
  var: 'thetao'
  # var: 'so'
  depth: '_0m'
  scenario: 'ssp26'
  # scenario: 'ssp85'
  type: 'histclim'
  # stat: !r NULL
  stat: "all_time_mean"
  location: 'full'
  pred_model: 'growth_rate'
  # pred_model: 'CTX_rate'
  contour_labs: FALSE
  cbar_ticks_int: 1
  contours_major: TRUE
  contours_minor: FALSE
  cbar: TRUE
  include_title: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries ----
```{r}
## Load libraries ----
library(tidyverse)
library(raster)
library(purrr)
library(khroma)
library(RColorBrewer)
library(terra)
library(glue)
library(here)
```


## Source helper functions -----
```{r}

source(file.path(here() %>% dirname(), 'catalyst-bHABS','utils','catalyst_helper_functions.R')) # UPDATE ME!
source(here('utils','00_catalyst_helper_functions_MS.R'))
```

```{r}
## Source dynamically set param values based on var -----
source(here('utils', '00_params_rmd_plot_setup.R'))
```

## Set spp name -----
```{r}
params$spp <- 'G.polynesiensis'
```


## Load Preds List ----

```{r}
if(is.null(params$stat)){
  pred_ras_histclim <- loadRData(here('data', 'preds',
                                   glue('preds_df_list_{params$pred_model}_histclim_glorys.rdata'))) |> stack()
} else if (params$stat == "all_time_mean"){
  pred_ras_histclim <- loadRData(here('data', 'preds',
                                   glue('preds_df_list_{params$pred_model}_histclim_glorys_{params$stat}.rdata'))) |> stack()
}

pred_ras_ssp26 <- loadRData(here('data', 'preds',
                                   glue('preds_df_list_{params$pred_model}_ssp26_gcm.rdata'))) |> stack()

pred_ras_ssp85 <- loadRData(here('data', 'preds',
                                   glue('preds_df_list_{params$pred_model}_ssp85_gcm.rdata'))) |> stack()


```


### Downsample GLORYS to match GCMs?? -----
```{r}
### Spatially aggregate to match resolutions (1 x 1 degree gcm layer) ----
res <- res(pred_ras_ssp26)[1]
glorys_pred_resamp <- terra::resample(pred_ras_histclim, pred_ras_ssp26, method="bilinear")
```


## Get Diffs (Future - Current) ----
```{r}
# SSP 2.6 - Glorys ----
gg_diff_ssp26_glorys <- pred_ras_ssp26 - glorys_pred_resamp

gg_diff_ssp26_glorys_df <- as(gg_diff_ssp26_glorys,"Raster") %>% ras2pts()


# SSP 8.5 - Glorys ----
gg_diff_ssp85_glorys <- pred_ras_ssp85 - glorys_pred_resamp

gg_diff_ssp85_glorys_df <- as(gg_diff_ssp85_glorys,"Raster") %>% ras2pts()


```


## Get Diffs (Future 8.5 - Future 2.6) ----
```{r}
# SSP 8.5 - SSP 2.6 ----
gg_diff_ssp85_ssp26 <- pred_ras_ssp85 - pred_ras_ssp26

gg_diff_ssp85_ssp26_df <- as(gg_diff_ssp85_ssp26,"Raster") %>% ras2pts()

```



## Set up plot params -----
### Get world map ----
```{r}
# ## Set variables ----
mapdata <- ggplot2::map_data("world", wrap = c(-25, 335), ylim = c(-75, 75)) %>%
  filter(long >= 100 & long <= 210)

```

### Set bbox -----
```{r}
bbox <- tibble(xmin = 120, xmax = 210, ymin = -60, ymax = 60, xstep = 10, ystep = -10)

```

### Set color pal
```{r}
# # color pal
# smooth_rainbow <- khroma::colour("smooth rainbow")
# # cpal <- smooth_rainbow(length(seq(0, 100, 1)), range = c(0, 0.9));
# cpal <- c(smooth_rainbow(length(seq(0, 0.25, length=100)), range = c(0, 0.9)), "#9e2a2b", "firebrick4")#, "#540b0e")
# cpal <- rev(cpal)


div_pal <- rev(c(rev(brewer.pal(9, "YlOrRd")),"white", brewer.pal(9, "Blues")))
```


### Set cbar legend title -----
```{r}
if(params$pred_model == "growth_rate"){
  cbar_title = "Difference in \nGrowth Rate \n(div/day)\n"

} else if(params$pred_model == "CTX_rate"){
  cbar_title = "Difference in \nTotal CTX \nProduction Rate \n(ng/ml/day)\n"
}
```


### Local function to plot maps -----
```{r}

plot_preds_diff_map <- function(diff_df, cbar_title = cbar_title){

   g <-  plot_var(data=diff_df, mapdata, bbox, cpal = div_pal, .interp=TRUE, .legend = TRUE) 
   
   gg <- g + add_border() + resize_cbar(27) +
    #  
    # add_minor_contour_lines(df=diff_df |>
    #                           mutate(val = value, lon=x, lat=y),
    #                           contours = .contours_minor, linewidth = 0.5) +
    add_major_contour_lines(df=diff_df |>
                              mutate(val = value, lon=x, lat=y), 
                              contours = .contours_major, linewidth = 0.75) +
    add_basemap() 
   
  
    gg_formatted <- gg %>%
      addColorBar(., 
          div_pal[1:18],
          limits=limits,   
          breaks=breaks,
          cbar_labels=cbar_labels,
          
          plot_type = "continuous") +
      # labs(fill = ifelse(params$pred_model == 'growth_rate', 
      #                  'Difference in \nGrowth Rate \n(div/day)\n', 
      #                  'Difference in Total CTX \nProduction Rate \n(ng/ml/day)\n')) +    
    
      rename_legend(title = cbar_title)
    
  return(gg_formatted)
}

```


### Set Plot Limits ----
```{r}

if(params$pred_model == "growth_rate"){
  
  .contours_major <- seq(-0.2, 0.2, 0.1)
  .contours_minor <- seq(-0.2, 0.2, 0.05)
  
  limits = c(-0.25,0.25)
  breaks = seq(-0.25, 0.25, 0.05)
  cbar_labels = seq(-0.25, 0.25, 0.05)
  
} else if(params$pred_model == "CTX_rate"){
  
  .contours_major <- seq(-0.6, 0.6, 0.2) 
  .contours_minor <- seq(-0.6, 0.6, 0.2)
  
  limits = c(-0.6,0.6)
  breaks = seq(-0.6,0.6,0.1) %>% round(., 2)
  cbar_labels = seq(-0.6,0.6,0.1)  %>% round(., 2)
  
}

```



## Plot Diffs ---
```{r}

# SSP 2.6 - Glorys ----
gg_diff_ssp26_glorys_pred <- plot_preds_diff_map(diff_df = gg_diff_ssp26_glorys_df, cbar_title = cbar_title)


# SSP 8.5 - Glorys ----
gg_diff_ssp85_glorys_pred <- plot_preds_diff_map(diff_df = gg_diff_ssp85_glorys_df, cbar_title = cbar_title)


# SSP 8.5 - SSP 2.6 ----
gg_diff_ssp85_ssp26_pred <- plot_preds_diff_map(diff_df = gg_diff_ssp85_ssp26_df, cbar_title = cbar_title)

```


### Save with Pos Preds ----
```{r}

gg_list <- list(gg_diff_ssp26_glorys_pred, gg_diff_ssp85_glorys_pred, gg_diff_ssp85_ssp26_pred)
names(gg_list) <- c(glue('pred_map_diff_ssp26_glorys_{params$pred_model}_pos_vals'),
                    glue('pred_map_diff_ssp85_glorys_{params$pred_model}_pos_vals'),
                    glue('pred_map_diff_ssp85_ssp26_{params$pred_model}_pos_vals'))


  gg_fnames <-  here('figs', glue('{names(gg_list)}.png')) |> as.list()

## save - this works (so does the above commented out option)
walk2(
  gg_fnames,
      gg_list,
  \(path, plot) ggsave(path, plot, width = 8)
)
  
```


## Crop Figs ----
### Sort Files in Chron Order
```{r}
# create movie
library(gtools)


# List plots files
flist <- list.files(here('figs'),pattern = "pred_map_diff",full.names=T)
plot_files <- flist#[grepl(glue("_{env_info$eov}"), flist, fixed=TRUE)] 

plot_files_extent <- plot_files#[grepl(p_extent, plot_files, fixed=TRUE)] 

pfiles <- plot_files_extent[order(basename(plot_files_extent))]

pfiles <- gtools::mixedsort(pfiles)

```

# Crop PNG Frames
```{r }
# #intermediate step to crop PNG file and reduce negative space

## use crop image source function ------
source(here('utils','crop_image.R'))
crop_image(pfiles)

```


## Save RData ----
```{r}
## Save rdata ---- (for ms fig formatting)
save(
  gg_diff_ssp26_glorys_pred, 
  gg_diff_ssp85_glorys_pred, 
  gg_diff_ssp85_ssp26_pred,
  
    file = here('data', 'gg_data', glue('gg_pred_diff_maps_{params$pred_model}.rdata')))

```
